# Generated by Django 2.2.6 on 2019-12-12 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(blank=True, max_length=150, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=150, null=True)),
                ('identificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de Creacion')),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activa'), ('P', 'Pendiente'), ('F', 'Finalizada'), ('V', 'Vencida'), ('C', 'Cancelada')], max_length=1, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='identificacion',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='telefono',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Cliente'),
        ),
    ]
